# .github/workflows/my-project.yml
name: CatanStats

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - run: mise install tuist@3
      - run: mise use tuist@latest
      - run: tuist test
